name: Flyway Migration
# thanks to https://haha.world/recipe-gh-action-cloud-sql/
on: push
    # branches:
    #   - main
env:
  PROJECT_ID: 'playground-geo' # TODO: update Google Cloud project id
  REGION: 'us-central1' # TODO: update Cloud Run service region
  gcp-cloud-sql-instance: 'crud-fastapi-db'

jobs:
  migration:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - id: 'auth'
      #   uses: 'google-github-actions/auth@v1'
      #   with:
      #     credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - id: 'auth'
        name: Google Auth
        uses: 'google-github-actions/auth@v1'
        with:
                                      #  projects/643420178383/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          workload_identity_provider: 'projects/643420178383/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'my-service-account@playground-geo.iam.gserviceaccount.com'
          # workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          # service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}' # e.g. - my-service-account@my-project.iam.gserviceaccount.com


      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      # - name: 'Use gcloud CLI'
        # run: 'gcloud info'

      # - name: gcloud install dependencies
      #   uses: GoogleCloudPlatform/github-actions/setup-gcloud@v1.1.1
      #   with:
      #     project_id: ${{ env.PROJECT_ID }}
      #     service_account_key: ${{ secrets.GCP_CREDENTIALS }}
      #     export_default_credentials: true

      - name: Cloud SQL Connect
        run: |
          gcloud config get-value account

      # gcloud sql connect ${{env.gcp-cloud-sql-instance}} --user=postgres

      - name: Backup staging database
        run: |
          gcloud sql backups create --instance=${{env.gcp-cloud-sql-instance}}

      - name: Run Flyway Migration
        run: echo "FLYWAY! might connect"
        # run: |
        #   docker run --rm \
        #   -v ${{ github.workspace }}/crud-fastapi/migrations:/flyway/sql \
        #   flyway/flyway:9 \
        #   -url=jdbc:postgresql://localhost:5432/crud_fastapi_app \
        #   -user=crud_fastapi_app \
        #   -password=${{ secrets.FASTAPI_CRUD_DB_PASS }} \
        #   migrate

      # - name: Set up JDK 1.8
      #   uses: actions/setup-java@v2
      #   with:
      #     java-version: '8'
      #     distribution: 'adopt'

      # - name: Cache Flyway
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/flyway
      #     key: ${{ runner.os }}-flyway-${{ hashFiles('**/flyway*.conf') }}

      # - name: Download Flyway
      #   run: |
      #     mkdir -p ~/flyway
      #     curl -L https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/7.15.0/flyway-commandline-7.15.0-linux-x64.tar.gz -o ~/flyway/flyway-commandline.tar.gz
      #     tar -xzf ~/flyway/flyway-commandline.tar.gz --strip-components=1 -C ~/flyway

      # - name: Run Flyway Migrate
      #   run: ~/flyway/flyway -user="crud_fastapi_app" -password="${{ secrets.FASTAPI_CRUD_DB_PASS }}" -url="jdbc:postgresql:///localhost:5432/crud_fastapi_app" -locations="filesystem:/crud-fastapi/migrationsl" migrate
