name: "Helm"

on: [push]


jobs:
  checkout-repo:
    runs-on: ubuntu-latest

    steps:
      # Checks out the repository in the current folder.
      - name: Checks out repository
        uses: actions/checkout@v3


  create-helm-folder:
    needs: checkout-repo
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        shell: bash
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: show value
        run: |
          echo ${GITHUB_REF} \
          pwd

      - name: Create report file
        run: cp -r party-ingest-core/ ${{ steps.vars.outputs.short_ref }}

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Commit report
        run: |
          git add .
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "Automated Helm folder"
          git push
