name: Docker Test

on: push

concurrency: tests-${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest

    services:
        # Only start the service for PRs against the main branch
        # if: github.event.pull_request.base.ref == 'main'
        postgres:
          image: postgres:14
          env:
            POSTGRES_USER: fastapi-crud-app
            POSTGRES_PASSWORD: pass
            # POSTGRES_DB: fastapi-crud-db
          ports:
            - 5432:5432



    steps:
    - uses: actions/checkout@v3
    - name: Set build tag
      id: date
      run: echo "::set-output name=tag::$(date +%s)"

    - name: Build the test Docker image
      working-directory: ./${{secrets.APP_NAME}}
      run: docker build . --file Dockerfile --tag ${{secrets.APP_NAME}}:${{ steps.date.outputs.tag }} --target test

    - name: Run integration tests against dev database.
    #   if: github.event.pull_request.base.ref == 'main'
      working-directory: ./${{secrets.APP_NAME}}
      run: docker run --network host -e FASTAPI_CRUD_DB_HOST=localhost -e FASTAPI_CRUD_DB_BASE=postgres -e FASTAPI_CRUD_DB_HOST=pass ${{secrets.APP_NAME}}:${{ steps.date.outputs.tag }} pytest -vv src/tests/integration
