name: Docker Test

on: push

concurrency: tests-${{ github.sha }}

env:
  APP_NAME: 'playground-geo'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set build tag
      id: date
      run: echo "::set-output name=tag::$(date +%s)"

    - name: Build the test Docker image
      working-directory: ./${{vars.APP_NAME}}
      run: docker build . --file Dockerfile --tag ${{vars.APP_NAME}}:${{ steps.date.outputs.tag }} --target test
